/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartcity.Form;

import java.awt.Color;
import smartcity.methodForm.Search.SearchResidents;
import smartcity.methodForm.Search.SearchAdmin;
import smartcity.methodForm.Search.SearchApartment;
import smartcity.methodForm.Search.SearchVehicle;



/**
 *
 * @author datd6
 */
public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
        //set button color 
        btnAdmins.setBackground(Color.LIGHT_GRAY);
        btnApartments.setBackground(Color.LIGHT_GRAY);
        btnResedents.setBackground(Color.LIGHT_GRAY);
        btnHome.setBackground(Color.GREEN);
        btnVehicle.setBackground(Color.LIGHT_GRAY);
        btnUser.setBackground(Color.LIGHT_GRAY);
        //set Panel
        HomePanel.setVisible(true);
        ResidentsPanel.setVisible(false);
        AdminsPanel.setVisible(false);
        VehiclesPanel.setVisible(false);
        ApartmentsPanel.setVisible(false);
        InforUserPanel.setVisible(false);
        AccountPanel.setVisible(false);
        //An cac nut chinh sua
        btnAdd.hide();
        btnDelete.hide();
        btnSearch.hide();
        btnMend.hide();
        //ngan chinh sua o InforUserPanel
        txtLastName.disable();
        txtFirstName.disable();
        txtPhoneNumber.disable();
        txtHomeTown.disable();
        txtEmail.disable();
        txtAdminIC.disable();
        cbDay.disable();
        cbGender.disable();
        cbMonth.disable();
        cbYear.disable();
        //an cac file AccountPanel
        txtUsername.disable();
        txtPassword.disable();
        txtCFPassword.hide();
        txtNewPassword.hide();
        lbCFPassword.hide();
        lbNewPassword.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        HomePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTotalResidents = new javax.swing.JLabel();
        txtTotalApartments = new javax.swing.JLabel();
        txtTotalVehicles = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnMend = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        ResidentsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbResidents = new javax.swing.JTable();
        AdminsPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbAdmins = new javax.swing.JTable();
        VehiclesPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbVehicles = new javax.swing.JTable();
        ApartmentsPanel = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tbApartments = new javax.swing.JTable();
        InforUserPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtHomeTown = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtAdminIC = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        btnMendInfor = new javax.swing.JButton();
        cbGender = new javax.swing.JComboBox<>();
        cbDay = new javax.swing.JComboBox<>();
        cbMonth = new javax.swing.JComboBox<>();
        cbYear = new javax.swing.JComboBox<>();
        AccountPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lbNewPassword = new javax.swing.JLabel();
        lbCFPassword = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnChangePassword = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        txtCFPassword = new javax.swing.JPasswordField();
        btnHome = new javax.swing.JButton();
        btnResedents = new javax.swing.JButton();
        btnApartments = new javax.swing.JButton();
        btnVehicle = new javax.swing.JButton();
        btnAdmins = new javax.swing.JButton();
        btnUser = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Số cư dân đang ở");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tổng số căn hộ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tổng số phương tiện");

        txtTotalResidents.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotalResidents.setText("00");

        txtTotalApartments.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotalApartments.setText("00");

        txtTotalVehicles.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotalVehicles.setText("00");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalApartments, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalResidents, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(542, 542, 542))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotalVehicles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txtTotalApartments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtTotalResidents, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd.setText("Thêm");

        btnMend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMend.setText("Sửa");
        btnMend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMendActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete.setText("Xóa");

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tbResidents.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tbResidents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "Giới tính", "Ngày sinh", "CMND/CCCD", "Số điện thoại", "Nghề nghiệp", "Quê quán", "Số căn hộ", "Ngày bắt đầu"
            }
        ));
        tbResidents.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbResidents.setFillsViewportHeight(true);
        tbResidents.setShowGrid(true);
        jScrollPane1.setViewportView(tbResidents);
        if (tbResidents.getColumnModel().getColumnCount() > 0) {
            tbResidents.getColumnModel().getColumn(0).setPreferredWidth(120);
            tbResidents.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbResidents.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbResidents.getColumnModel().getColumn(3).setPreferredWidth(120);
            tbResidents.getColumnModel().getColumn(4).setPreferredWidth(120);
            tbResidents.getColumnModel().getColumn(5).setPreferredWidth(120);
            tbResidents.getColumnModel().getColumn(6).setPreferredWidth(120);
            tbResidents.getColumnModel().getColumn(7).setPreferredWidth(250);
            tbResidents.getColumnModel().getColumn(8).setPreferredWidth(120);
            tbResidents.getColumnModel().getColumn(9).setPreferredWidth(120);
        }

        javax.swing.GroupLayout ResidentsPanelLayout = new javax.swing.GroupLayout(ResidentsPanel);
        ResidentsPanel.setLayout(ResidentsPanelLayout);
        ResidentsPanelLayout.setHorizontalGroup(
            ResidentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResidentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        ResidentsPanelLayout.setVerticalGroup(
            ResidentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResidentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
        );

        jScrollPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tbAdmins.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tbAdmins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CMND/CCCD", "Tên", "Giới tính", "Ngày sinh", "Số điện thoại", "Nghề nghiệp", "Quê quán", "Ngày bắt đầu", "Account"
            }
        ));
        tbAdmins.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbAdmins.setFillsViewportHeight(true);
        tbAdmins.setShowGrid(true);
        jScrollPane5.setViewportView(tbAdmins);
        if (tbAdmins.getColumnModel().getColumnCount() > 0) {
            tbAdmins.getColumnModel().getColumn(0).setPreferredWidth(120);
            tbAdmins.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbAdmins.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbAdmins.getColumnModel().getColumn(3).setPreferredWidth(120);
            tbAdmins.getColumnModel().getColumn(4).setPreferredWidth(120);
            tbAdmins.getColumnModel().getColumn(5).setPreferredWidth(120);
            tbAdmins.getColumnModel().getColumn(6).setPreferredWidth(120);
            tbAdmins.getColumnModel().getColumn(7).setPreferredWidth(250);
            tbAdmins.getColumnModel().getColumn(8).setPreferredWidth(120);
        }

        javax.swing.GroupLayout AdminsPanelLayout = new javax.swing.GroupLayout(AdminsPanel);
        AdminsPanel.setLayout(AdminsPanelLayout);
        AdminsPanelLayout.setHorizontalGroup(
            AdminsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE))
        );
        AdminsPanelLayout.setVerticalGroup(
            AdminsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
        );

        jScrollPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tbVehicles.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tbVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID chủ sở hữu", "Loại phương tiện", "Phí gửi chưa thanh toán"
            }
        ));
        tbVehicles.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbVehicles.setFillsViewportHeight(true);
        tbVehicles.setShowGrid(true);
        jScrollPane6.setViewportView(tbVehicles);
        if (tbVehicles.getColumnModel().getColumnCount() > 0) {
            tbVehicles.getColumnModel().getColumn(0).setPreferredWidth(120);
            tbVehicles.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbVehicles.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        javax.swing.GroupLayout VehiclesPanelLayout = new javax.swing.GroupLayout(VehiclesPanel);
        VehiclesPanel.setLayout(VehiclesPanelLayout);
        VehiclesPanelLayout.setHorizontalGroup(
            VehiclesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehiclesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE))
        );
        VehiclesPanelLayout.setVerticalGroup(
            VehiclesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehiclesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
        );

        jScrollPane11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tbApartments.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tbApartments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Chủ hộ", "Căn hộ sô", "Tình trạng", "Diện tích", "Tiền điện", "Tiền nước", "Phí dịch vụ "
            }
        ));
        tbApartments.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbApartments.setFillsViewportHeight(true);
        tbApartments.setShowGrid(true);
        jScrollPane11.setViewportView(tbApartments);
        if (tbApartments.getColumnModel().getColumnCount() > 0) {
            tbApartments.getColumnModel().getColumn(0).setPreferredWidth(120);
            tbApartments.getColumnModel().getColumn(1).setPreferredWidth(120);
            tbApartments.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbApartments.getColumnModel().getColumn(3).setPreferredWidth(120);
            tbApartments.getColumnModel().getColumn(4).setPreferredWidth(120);
            tbApartments.getColumnModel().getColumn(5).setPreferredWidth(120);
            tbApartments.getColumnModel().getColumn(6).setPreferredWidth(120);
        }

        javax.swing.GroupLayout ApartmentsPanelLayout = new javax.swing.GroupLayout(ApartmentsPanel);
        ApartmentsPanel.setLayout(ApartmentsPanelLayout);
        ApartmentsPanelLayout.setHorizontalGroup(
            ApartmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ApartmentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE))
        );
        ApartmentsPanelLayout.setVerticalGroup(
            ApartmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ApartmentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tên");
        jLabel4.setMaximumSize(new java.awt.Dimension(56, 17));
        jLabel4.setMinimumSize(new java.awt.Dimension(56, 17));
        jLabel4.setPreferredSize(new java.awt.Dimension(56, 17));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Số điện thoại");
        jLabel5.setMaximumSize(new java.awt.Dimension(56, 17));
        jLabel5.setMinimumSize(new java.awt.Dimension(56, 17));
        jLabel5.setPreferredSize(new java.awt.Dimension(56, 17));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ngày sinh");
        jLabel6.setMaximumSize(new java.awt.Dimension(56, 17));
        jLabel6.setMinimumSize(new java.awt.Dimension(56, 17));
        jLabel6.setPreferredSize(new java.awt.Dimension(56, 17));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Giới tính");
        jLabel7.setMaximumSize(new java.awt.Dimension(56, 17));
        jLabel7.setMinimumSize(new java.awt.Dimension(56, 17));
        jLabel7.setPreferredSize(new java.awt.Dimension(56, 17));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Số CMND/CCCD");
        jLabel8.setMaximumSize(new java.awt.Dimension(56, 17));
        jLabel8.setMinimumSize(new java.awt.Dimension(56, 17));
        jLabel8.setPreferredSize(new java.awt.Dimension(56, 17));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Email");
        jLabel9.setMaximumSize(new java.awt.Dimension(56, 17));
        jLabel9.setMinimumSize(new java.awt.Dimension(56, 17));
        jLabel9.setPreferredSize(new java.awt.Dimension(56, 17));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Quê quán");
        jLabel10.setMaximumSize(new java.awt.Dimension(56, 17));
        jLabel10.setMinimumSize(new java.awt.Dimension(56, 17));
        jLabel10.setPreferredSize(new java.awt.Dimension(56, 17));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Họ");

        txtLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLastName.setText("Nguyen");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setText("123@gmail.com");

        txtHomeTown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHomeTown.setText("Hà Đông, Hà Nội");

        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstName.setText("A");

        txtAdminIC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAdminIC.setText("123456789");

        txtPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPhoneNumber.setText("0123456789");

        btnMendInfor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMendInfor.setText("Sửa");
        btnMendInfor.setPreferredSize(new java.awt.Dimension(139, 31));
        btnMendInfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMendInforActionPerformed(evt);
            }
        });

        cbGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        cbDay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cbYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));

        javax.swing.GroupLayout InforUserPanelLayout = new javax.swing.GroupLayout(InforUserPanel);
        InforUserPanel.setLayout(InforUserPanelLayout);
        InforUserPanelLayout.setHorizontalGroup(
            InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InforUserPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InforUserPanelLayout.createSequentialGroup()
                        .addComponent(cbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                        .addComponent(btnMendInfor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(InforUserPanelLayout.createSequentialGroup()
                        .addGroup(InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLastName)
                                .addComponent(txtFirstName)
                                .addComponent(txtHomeTown, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                                .addComponent(txtEmail)
                                .addComponent(txtAdminIC)
                                .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        InforUserPanelLayout.setVerticalGroup(
            InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InforUserPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMendInfor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminIC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InforUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHomeTown, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Password");
        jLabel12.setMaximumSize(new java.awt.Dimension(56, 17));
        jLabel12.setMinimumSize(new java.awt.Dimension(56, 17));
        jLabel12.setPreferredSize(new java.awt.Dimension(56, 17));

        lbNewPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNewPassword.setText("New Password");
        lbNewPassword.setMaximumSize(new java.awt.Dimension(56, 17));
        lbNewPassword.setMinimumSize(new java.awt.Dimension(56, 17));
        lbNewPassword.setPreferredSize(new java.awt.Dimension(56, 17));

        lbCFPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCFPassword.setText("Confirm Password");
        lbCFPassword.setMaximumSize(new java.awt.Dimension(56, 17));
        lbCFPassword.setMinimumSize(new java.awt.Dimension(56, 17));
        lbCFPassword.setPreferredSize(new java.awt.Dimension(56, 17));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Username");

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setText("admin");

        btnChangePassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnChangePassword.setText("Đổi mật khẩu");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        txtPassword.setText("jPasswordField1");

        javax.swing.GroupLayout AccountPanelLayout = new javax.swing.GroupLayout(AccountPanel);
        AccountPanel.setLayout(AccountPanelLayout);
        AccountPanelLayout.setHorizontalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbCFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                                .addComponent(txtPassword)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        AccountPanelLayout.setVerticalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AccountPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(HomePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnMend, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ResidentsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(AdminsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(VehiclesPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ApartmentsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(InforUserPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(AccountPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResidentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMend, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(AdminsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(165, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(VehiclesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(164, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ApartmentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(163, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(InforUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(AccountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(48, 48, 48)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnMend, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ResidentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(HomePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdminsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(VehiclesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ApartmentsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(InforUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(AccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        btnHome.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnHome.setText("Trang chủ");
        btnHome.setMaximumSize(new java.awt.Dimension(150, 35));
        btnHome.setMinimumSize(new java.awt.Dimension(137, 33));
        btnHome.setPreferredSize(new java.awt.Dimension(137, 33));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnResedents.setBackground(new java.awt.Color(204, 255, 204));
        btnResedents.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnResedents.setText("Cư dân");
        btnResedents.setMaximumSize(new java.awt.Dimension(150, 35));
        btnResedents.setMinimumSize(new java.awt.Dimension(137, 33));
        btnResedents.setPreferredSize(new java.awt.Dimension(137, 33));
        btnResedents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResedentsActionPerformed(evt);
            }
        });

        btnApartments.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnApartments.setText("Căn hộ");
        btnApartments.setMaximumSize(new java.awt.Dimension(150, 35));
        btnApartments.setMinimumSize(new java.awt.Dimension(137, 33));
        btnApartments.setPreferredSize(new java.awt.Dimension(137, 33));
        btnApartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApartmentsActionPerformed(evt);
            }
        });

        btnVehicle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnVehicle.setText("Phương tiện");
        btnVehicle.setMaximumSize(new java.awt.Dimension(150, 35));
        btnVehicle.setMinimumSize(new java.awt.Dimension(137, 33));
        btnVehicle.setPreferredSize(new java.awt.Dimension(137, 33));
        btnVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleActionPerformed(evt);
            }
        });

        btnAdmins.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAdmins.setText("Ban quản lý");
        btnAdmins.setMaximumSize(new java.awt.Dimension(150, 35));
        btnAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminsActionPerformed(evt);
            }
        });

        btnUser.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hồ sơ", "Tài khoản", "Đăng xuất" }));
        btnUser.setMaximumSize(new java.awt.Dimension(150, 35));
        btnUser.setMinimumSize(new java.awt.Dimension(137, 33));
        btnUser.setPreferredSize(new java.awt.Dimension(137, 33));
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResedents, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addGap(14, 14, 14)
                        .addComponent(btnApartments, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdmins, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUser, 0, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResedents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnApartments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdmins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        btnUser.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResedentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResedentsActionPerformed
        // TODO add your handling code here:
        //set button color 
        btnAdmins.setBackground(Color.LIGHT_GRAY);
        btnApartments.setBackground(Color.LIGHT_GRAY);
        btnResedents.setBackground(Color.GREEN);
        btnHome.setBackground(Color.LIGHT_GRAY);
        btnVehicle.setBackground(Color.LIGHT_GRAY);
        btnUser.setBackground(Color.LIGHT_GRAY);
        //set Panel
        HomePanel.setVisible(false);
        ResidentsPanel.setVisible(true);
        AdminsPanel.setVisible(false);
        VehiclesPanel.setVisible(false);
        ApartmentsPanel.setVisible(false);
        InforUserPanel.setVisible(false);
        AccountPanel.setVisible(false);
        btnAdd.show();
        btnDelete.show();
        btnSearch.show();
        btnMend.show();
    }//GEN-LAST:event_btnResedentsActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        //set button color 
        btnAdmins.setBackground(Color.LIGHT_GRAY);
        btnApartments.setBackground(Color.LIGHT_GRAY);
        btnResedents.setBackground(Color.LIGHT_GRAY);
        btnHome.setBackground(Color.LIGHT_GRAY);
        btnVehicle.setBackground(Color.LIGHT_GRAY);
        btnUser.setBackground(Color.GREEN);
        //select method
        String select=(String)btnUser.getSelectedItem();
        if(select.equals("Đăng xuất")){
            this.setVisible(false);
            new LoginForm().setVisible(true);
        }
        else if(select.equals("Hồ sơ")){
            HomePanel.setVisible(false);
            ResidentsPanel.setVisible(false);
            AdminsPanel.setVisible(false);
            VehiclesPanel.setVisible(false);
            ApartmentsPanel.setVisible(false);
            InforUserPanel.setVisible(true);
            AccountPanel.setVisible(false);
            btnAdd.hide();
            btnDelete.hide();
            btnSearch.hide();
            btnMend.hide();
        }
        else if(select.equals("Tài khoản")){
            HomePanel.setVisible(false);
            ResidentsPanel.setVisible(false);
            AdminsPanel.setVisible(false);
            VehiclesPanel.setVisible(false);
            ApartmentsPanel.setVisible(false);
            InforUserPanel.setVisible(false);
            AccountPanel.setVisible(true);
            btnAdd.hide();
            btnDelete.hide();
            btnSearch.hide();
            btnMend.hide();
        }
        
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        //set button color 
        btnAdmins.setBackground(Color.LIGHT_GRAY);
        btnApartments.setBackground(Color.LIGHT_GRAY);
        btnResedents.setBackground(Color.LIGHT_GRAY);
        btnHome.setBackground(Color.GREEN);
        btnVehicle.setBackground(Color.LIGHT_GRAY);
        btnUser.setBackground(Color.LIGHT_GRAY);
        //set Panel
        HomePanel.setVisible(true);
        ResidentsPanel.setVisible(false);
        AdminsPanel.setVisible(false);
        VehiclesPanel.setVisible(false);
        ApartmentsPanel.setVisible(false);
        InforUserPanel.setVisible(false);
        AccountPanel.setVisible(false);
        // set button
        btnAdd.hide();
        btnDelete.hide();
        btnSearch.hide();
        btnMend.hide();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleActionPerformed
        // TODO add your handling code here:
        //set button color 
        btnAdmins.setBackground(Color.LIGHT_GRAY);
        btnApartments.setBackground(Color.LIGHT_GRAY);
        btnResedents.setBackground(Color.LIGHT_GRAY);
        btnHome.setBackground(Color.LIGHT_GRAY);
        btnVehicle.setBackground(Color.GREEN);
        btnUser.setBackground(Color.LIGHT_GRAY);
        //set Panel
        HomePanel.setVisible(false);
        ResidentsPanel.setVisible(false);
        AdminsPanel.setVisible(false);
        VehiclesPanel.setVisible(true);
        ApartmentsPanel.setVisible(false);
        InforUserPanel.setVisible(false);
        AccountPanel.setVisible(false);
        //set method
        btnAdd.show();
        btnDelete.show();
        btnSearch.show();
        btnMend.show();
    }//GEN-LAST:event_btnVehicleActionPerformed

    private void btnAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminsActionPerformed
        // TODO add your handling code here:
        //set button color 
        btnAdmins.setBackground(Color.green);
        btnApartments.setBackground(Color.LIGHT_GRAY);
        btnResedents.setBackground(Color.LIGHT_GRAY);
        btnHome.setBackground(Color.LIGHT_GRAY);
        btnVehicle.setBackground(Color.LIGHT_GRAY);
        btnUser.setBackground(Color.LIGHT_GRAY);
        //set Panel
        HomePanel.setVisible(false);
        ResidentsPanel.setVisible(false);
        AdminsPanel.setVisible(true);
        VehiclesPanel.setVisible(false);
        ApartmentsPanel.setVisible(false);
        InforUserPanel.setVisible(false);
        AccountPanel.setVisible(false);
        //set button
        btnAdd.show();
        btnDelete.show();
        btnSearch.show();
        btnMend.show();
    }//GEN-LAST:event_btnAdminsActionPerformed

    private void btnApartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApartmentsActionPerformed
        // TODO add your handling code here:
        //set button color 
        btnAdmins.setBackground(Color.LIGHT_GRAY);
        btnApartments.setBackground(Color.green);
        btnResedents.setBackground(Color.LIGHT_GRAY);
        btnHome.setBackground(Color.LIGHT_GRAY);
        btnVehicle.setBackground(Color.LIGHT_GRAY);
        btnUser.setBackground(Color.LIGHT_GRAY);
        //set Panel
        HomePanel.setVisible(false);
        ResidentsPanel.setVisible(false);
        AdminsPanel.setVisible(false);
        VehiclesPanel.setVisible(false);
        ApartmentsPanel.setVisible(true);
        InforUserPanel.setVisible(false);
        AccountPanel.setVisible(false);
        //set method
        btnAdd.show();
        btnDelete.show();
        btnSearch.show();
        btnMend.show();
    }//GEN-LAST:event_btnApartmentsActionPerformed

    private void btnMendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMendActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(ResidentsPanel.isVisible()){
            new SearchResidents().setVisible(true);
        }
        else if(ApartmentsPanel.isVisible()){
            new SearchApartment().setVisible(true);
        }
        else if(VehiclesPanel.isVisible()){
            new SearchVehicle().setVisible(true);
        }
        else if(AdminsPanel.isVisible()){
            new SearchAdmin().setVisible(true);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnMendInforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMendInforActionPerformed
        // TODO add your handling code here:
        if(btnMendInfor.getText().equals("Sửa")){
            btnMendInfor.setText("Lưu");
            txtLastName.enable();
            txtFirstName.enable();
            txtPhoneNumber.enable();
            txtHomeTown.enable();
            txtEmail.enable();
            txtAdminIC.enable();
            cbDay.enable();
            cbGender.enable();
            cbMonth.enable();
            cbYear.enable();
        }
        else{
            btnMendInfor.setText("Sửa");
            txtLastName.disable();
            txtFirstName.disable();
            txtPhoneNumber.disable();
            txtHomeTown.disable();
            txtEmail.disable();
            txtAdminIC.disable();
            cbDay.disable();
            cbGender.disable();
            cbMonth.disable();
            cbYear.disable();
        }
    }//GEN-LAST:event_btnMendInforActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        if(btnChangePassword.getText().equals("Đổi mật khẩu")){
            txtPassword.setText("");
            btnChangePassword.setText("Lưu");
            txtPassword.enable();
            lbCFPassword.show();
            lbNewPassword.show();
            txtCFPassword.show();
            txtNewPassword.show();
        }
        else{
            txtPassword.setText("**********");
            btnChangePassword.setText("Đổi mật khẩu");
            txtPassword.disable();
            txtCFPassword.hide();
            txtNewPassword.hide();
            lbCFPassword.hide();
            lbNewPassword.hide();
        }
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountPanel;
    private javax.swing.JPanel AdminsPanel;
    private javax.swing.JPanel ApartmentsPanel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel InforUserPanel;
    private javax.swing.JPanel ResidentsPanel;
    private javax.swing.JPanel VehiclesPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdmins;
    private javax.swing.JButton btnApartments;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMend;
    private javax.swing.JButton btnMendInfor;
    private javax.swing.JButton btnResedents;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> btnUser;
    private javax.swing.JButton btnVehicle;
    private javax.swing.JComboBox<String> cbDay;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbMonth;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCFPassword;
    private javax.swing.JLabel lbNewPassword;
    private javax.swing.JTable tbAdmins;
    private javax.swing.JTable tbApartments;
    private javax.swing.JTable tbResidents;
    private javax.swing.JTable tbVehicles;
    private javax.swing.JTextField txtAdminIC;
    private javax.swing.JPasswordField txtCFPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHomeTown;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JLabel txtTotalApartments;
    private javax.swing.JLabel txtTotalResidents;
    private javax.swing.JLabel txtTotalVehicles;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
